name: Android Release

on:
  release:
    types: [created]
  push:
    tags:
      - "*"

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 19
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/release/**/*.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2
        with:
          name: app

      - name: Release APK
        uses: ncipollo/release-action@v1
        with:
          artifacts: "app/*.apk"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

env:
  APP_FOLDER: app