name: Android Release

on:
  release:
    types: [created]
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: ./github/actions/checkout@v2

      - name: Set up JDK
        uses: ./github/actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: ./github/actions/upload-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release-unsigned.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: ./github/actions/download-artifact@v2
        with:
          name: app-release
          path: app/build/outputs/apk/release

      - name: Get tag name
        run: |
          echo "VERSION_TAG=${GITHUB_REF/refs/tags/}" >> $GITHUB_ENV

      - name: Compute Checksums
        run: |
          sha256sum app/build/outputs/apk/release/app-release-unsigned.apk | tee checksums.txt
          while read -r line; do
            sha=$(echo $line | awk '{ print $1 }')
            echo "APK_SHA=$sha" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: ./github/actions/gh-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Release ${{ env.VERSION_TAG }}
          body: |
            ### Checksums

            | Variant | SHA-256 |
            | ------- | ------- |
            | app-release-unsigned.apk | ${{ env.APK_SHA }} |

          files: app/build/outputs/apk/release/app-release-unsigned.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
